name: Code-Validation_Test

on:
  push:
    branches:
      - main
      - sprint_2_submission

jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_CSS: false
          # VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JSCPD: false
